# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignInButtonTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signInButtonTest(self):
    # Test name: signInButtonTest
    # Step # | name | target | value
    # 1 | open | https://swesupply2023team22.xyz/ | 
    self.driver.get("https://swesupply2023team22.xyz/")
    # 2 | setWindowSize | 814x803 | 
    self.driver.set_window_size(814, 803)
    # 3 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 4 | type | id=username | testuser1
    self.driver.find_element(By.ID, "username").send_keys("testuser1")
    # 5 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 6 | type | id=password | T3st!@#$
    self.driver.find_element(By.ID, "password").send_keys("T3st!@#$")
    # 7 | click | id=togglePasswordSignIn | 
    self.driver.find_element(By.ID, "togglePasswordSignIn").click()
    # 8 | click | id=loginButton | 
    self.driver.find_element(By.ID, "loginButton").click()
  
