# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignUpFormTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signUpFormTest(self):
    # Test name: signUpFormTest
    # Step # | name | target | value
    # 1 | open | https://swe2023team22.xyz/signup | 
    self.driver.get("https://swe2023team22.xyz/signup")
    # 2 | setWindowSize | 1440x900 | 
    self.driver.set_window_size(1440, 900)
    # 3 | click | id=fName | 
    self.driver.find_element(By.ID, "fName").click()
    # 4 | type | id=fName | Taha
    self.driver.find_element(By.ID, "fName").send_keys("Taha")
    # 5 | type | id=lName | Lewis
    self.driver.find_element(By.ID, "lName").send_keys("Lewis")
    # 6 | type | id=email | testemail@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("testemail@gmail.com")
    # 7 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 8 | type | id=username | testuser
    self.driver.find_element(By.ID, "username").send_keys("testuser")
    # 9 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 10 | type | id=password | T3st!@#$
    self.driver.find_element(By.ID, "password").send_keys("T3st!@#$")
    # 11 | click | id=confirm-password | 
    self.driver.find_element(By.ID, "confirm-password").click()
    # 12 | type | id=confirm-password | T3st!@#$
    self.driver.find_element(By.ID, "confirm-password").send_keys("T3st!@#$")
    # 13 | click | css=.passwordCont | 
    self.driver.find_element(By.CSS_SELECTOR, ".passwordCont").click()
    # 14 | click | id=togglePasswordSignUp | 
    self.driver.find_element(By.ID, "togglePasswordSignUp").click()
    # 15 | click | id=togglePasswordSignUp2 | 
    self.driver.find_element(By.ID, "togglePasswordSignUp2").click()
    # 16 | click | id=signUp | 
    self.driver.find_element(By.ID, "signUp").click()
  
