# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSelectPluginButton():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_selectPluginButton(self):
    # Test name: selectPluginButton
    # Step # | name | target | value
    # 1 | open | https://swe2023team22.xyz/services | 
    self.driver.get("https://swe2023team22.xyz/services")
    # 2 | setWindowSize | 1039x803 | 
    self.driver.set_window_size(1039, 803)
    # 3 | click | css=.row:nth-child(1) > .pluginIcons:nth-child(1) .button | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(1) > .pluginIcons:nth-child(1) .button").click()
    # 4 | close |  | 
    self.driver.close()
  
